services:
  network-deploy-service:
    networks:
      - base_network

  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  db-config:
    extends:
      service: network-deploy-service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brFwm4-gnacF3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: brFwm4-gnacF3
      EUREKA_SERVER_URL: http://eurekaserver:8082/eureka/