spring:
  application:
    name: gatewayserver
  config:
    import: configserver:http://localhost:8081/
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true





management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

server:
  port: 8083

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8082/eureka/

