spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GRENI-BENI/nixel-config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8081
